### ISSUE TITLE
Suggestion: noun_chunks 

### ISSUE THREAD

**Issue by amrrs** [DevopediaOrg/twitter-hashtag-selector#5]
Great effort @ibrahim45  and @felsen - I saw that in TODO it's mentioned to extract noun verb combo for a perfect keyword. `doc.noun_chunks` is a good alternative. 

Eg: https://spacy.io/usage/linguistic-features

https://spacy.io/api/doc#noun_chunks

**Comment by ibrahimsha23** [comment]
@amrrs Really thankful for your appreciation. I will look into this!!
